# Generated by Django 2.1 on 2018-09-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='网站名')),
                ('introduction', models.CharField(max_length=100, verbose_name='简介')),
                ('powered', models.CharField(help_text='Copyright © 2018 Sing. Powered by Django.', max_length=100, verbose_name='设计者信息')),
                ('approval_number', models.CharField(max_length=100, verbose_name='审批号')),
            ],
            options={
                'verbose_name': '网站信息',
                'verbose_name_plural': '网站信息列表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ToolName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名')),
                ('slug', models.SlugField(unique=True, verbose_name='索引名')),
            ],
            options={
                'verbose_name': '工具箱',
                'verbose_name_plural': '工具箱列表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ToolParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='链接名')),
                ('link', models.URLField(help_text='请填写http或https开头的完整形式地址', verbose_name='友链地址')),
                ('img_link', models.URLField(help_text='请填写http或https开头的完整形式地址', null=True, verbose_name='图片地址')),
                ('introduction', models.TextField(null=True, verbose_name='简介')),
                ('tool_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.ToolName', verbose_name='工具分类')),
            ],
            options={
                'verbose_name': '工具',
                'verbose_name_plural': '工具列表',
                'ordering': ['id'],
            },
        ),
    ]
