# Generated by Django 2.1 on 2018-09-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.BookBase')),
                ('name', models.CharField(max_length=64, verbose_name='书名')),
                ('slug', models.SlugField(unique=True, verbose_name='索引后缀')),
                ('introduction', models.TextField(verbose_name='书的简介')),
                ('status_models', models.CharField(default='未完成，敬请期待', max_length=64, verbose_name='状态')),
                ('author', models.CharField(default='Sing', max_length=50, verbose_name='作者')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '书本',
                'verbose_name_plural': '图书馆',
                'ordering': ['id'],
            },
            bases=('books.bookbase',),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('bookbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.BookBase')),
                ('name', models.CharField(max_length=64, verbose_name='章节名')),
                ('slug', models.SlugField(unique=True, verbose_name='索引后缀')),
                ('body', models.TextField(verbose_name='章节内容')),
                ('page_num', models.IntegerField(help_text='替换Django自带的id值，用于控制章节顺序', verbose_name='顺序')),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='所属书名')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节列表',
                'ordering': ['page_num'],
            },
            bases=('books.bookbase',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('bookbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.BookBase')),
                ('name', models.CharField(max_length=64, verbose_name='小节名')),
                ('slug', models.SlugField(unique=True, verbose_name='索引后缀')),
                ('body', models.TextField(verbose_name='章节内容')),
                ('page_num', models.IntegerField(help_text='替换Django自带的id值，用于控制章节小节顺序', verbose_name='顺序')),
                ('chaptet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Chapter', verbose_name='所属章节')),
            ],
            options={
                'verbose_name': '章节小节',
                'verbose_name_plural': '章节小节列表',
                'ordering': ['page_num'],
            },
            bases=('books.bookbase',),
        ),
    ]
